import { CombinedCoin } from "@/types/Coin";

export const defaultArray = (): CombinedCoin[] => [
  {
    symbolBinance: "BCHUSDT",
    priceBinance: 2512.938,
    symbolParibu: "BCH_TL",
    paribuHighestBid: 2513.4,
    paribuLowestAsk: 2513.45,
    id: "BCHUSDTBCH_TL",
    buyDiff: 0.02,
    isBuy: false,
    sellDiff: -0.018,
    paribuDiff: 0.038,
    benefit: 1,
    priceBinanceReal: 1,
    paribuBuyPrice: 0,
  },
  {
    symbolBinance: "XLMUSDT",
    priceBinance: 2.1359403,
    symbolParibu: "XLM_TL",
    paribuHighestBid: 2.134,
    paribuLowestAsk: 2.136,
    id: "XLMUSDTXLM_TL",
    buyDiff: 0.003,
    isBuy: false,
    sellDiff: 0.091,
    paribuDiff: -0.088,
    benefit: 1,
    priceBinanceReal: 1,
    paribuBuyPrice: 1,
  },
  {
    symbolBinance: "XTZUSDT",
    priceBinance: 22.01644,
    symbolParibu: "XTZ_TL",
    paribuHighestBid: 21.6,
    paribuLowestAsk: 22.02,
    id: "XTZUSDTXTZ_TL",
    buyDiff: 0.016,
    isBuy: false,
    sellDiff: 1.891,
    paribuDiff: -1.875,
    priceBinanceReal: 1,
  },
  {
    symbolBinance: "BATUSDT",
    priceBinance: 5.377432,
    symbolParibu: "BAT_TL",
    paribuHighestBid: 5.35,
    paribuLowestAsk: 5.38,
    id: "BATUSDTBAT_TL",
    buyDiff: 0.048,
    isBuy: false,
    sellDiff: 0.51,
    paribuDiff: -0.462,
    paribuBuyPrice: 1,
    priceBinanceReal: 1,
  },
  {
    symbolBinance: "ZILUSDT",
    priceBinance: 0.5890036,
    symbolParibu: "ZIL_TL",
    paribuHighestBid: 0.5863,
    paribuLowestAsk: 0.5897,
    id: "ZILUSDTZIL_TL",
    buyDiff: 0.118,
    isBuy: false,
    sellDiff: 0.459,
    paribuDiff: -0.341,
    priceBinanceReal: 1,
  },
];
